// Code generated by BobGen mysql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"strings"

	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
)

var defaultFaker = faker.New()

func random_CountryContinent(f *faker.Faker) CountryContinent {
	if f == nil {
		f = &defaultFaker
	}

	all := allCountryContinent()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_CountrylanguageIsOfficial(f *faker.Faker) CountrylanguageIsOfficial {
	if f == nil {
		f = &defaultFaker
	}

	all := allCountrylanguageIsOfficial()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_decimal_Decimal(f *faker.Faker) decimal.Decimal {
	if f == nil {
		f = &defaultFaker
	}

	return decimal.New(f.Int64Between(0, 1000), 0)
}

func random_int16(f *faker.Faker) int16 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int16()
}

func random_int32(f *faker.Faker) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_string(f *faker.Faker) string {
	if f == nil {
		f = &defaultFaker
	}

	return strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
}
