// Code generated by BobGen mysql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "github.com/ishisaka/golang-bob-plactice/models"

type (
	CountryContinent          = models.CountryContinent
	CountrylanguageIsOfficial = models.CountrylanguageIsOfficial
)

func allCountryContinent() []CountryContinent {
	return models.AllCountryContinent()
}

func allCountrylanguageIsOfficial() []CountrylanguageIsOfficial {
	return models.AllCountrylanguageIsOfficial()
}
